{% set version = "3.0.7" %}

package:
  name: chaospy
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: c8aef5601ad7300515efe2355afc38799f23dd1e19f7590f792e6d4b82913c65

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - pytest-runner
  commands:
    - py.test

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
