{% set version = "3.2.4" %}

package:
  name: chaospy
  version: {{ version }}

source:
  fn: chaospy-{{ version }}.tar.gz
  url: https://github.com/jonathf/chaospy/archive/v{{ version }}.tar.gz
  sha256: 4a6bf09374002f853e56d3600efc198160a51c7c857c56334c163f6c40d3f8a1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - networkx
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - chaospy
  source_files:
    - tests
  requires:
    - pytest-runner
  commands:
    - py.test

about:
  home: https://github.com/jonathf/chaospy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Toolbox for performing uncertainty quantification

extra:
  recipe-maintainers:
    - jschueller
