travis:
  secure:
    BINSTAR_TOKEN: iqdKvwYYPMhl5Uubyr0EqHtcYCU4Uw1N8iIIhDw8rsSLjceNkvh3olUQTaFkOwgV7vGfEbekGuHVAMcckKIGlTFrw9lrOjYUU+4V6yCZUxWCt/Exs1CArkMVei0oJMnnE9j0VAwddP3bKGmb48euJgbAYZE0j8ykr2YA555PqgTgk7IStxwg40NL6LBNRadP3XwWDFoKBtBOjVq/llus+4OwjGm8dKj35IRzX77mjiF8YBscDZq7sXKN5rdNmH6O57qwWTAeLKWzjQJ7ef3/i/1nrXaTCBRnAm7R/AAElwR3S1KKbJOWr/ih7QUf/pywiRLgZA7u4b9kq1/rq12yDRuhQgFlsjMo7cset8M6NtoVFB3Dxm7xij2LCkrGkvf5BDc/ngX5mxJ0DmB6kSoeavpcPyB2f3jFddUIP712MYJS68szwwiKpCdEtLHp0AQnWExZSs2DL7YFJKAuTKj1JBOCeRAF+vjta15kl+TBh+PFcd5IHTwSItn1OgK7VfytTZrCN9A+GuFtaAZSDwsrzCDeXHrHQfFdyjrdUsieUPwl9tlgkajc0OHto76vi4bVKk4o9Q6yCgel6NmhPgPbgXMpvj7qiYzCqB91tqx0WVoBJa1/xBL3LbeRP0rDGot0RIW2sKBrEtVWUxw+XvH330QG/OOAKMVhCIAZmLpgrGo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
